### ISSUE TITLE
8266 example colon timing

### ISSUE THREAD

**Issue by tablatronix** [witnessmenow/WiFi-Tetris-Clock#2]
`    oneSecondLoopDue = now + 10000;`

was that supposed to be 1 second? 😄

**Comment by tablatronix** [comment]
I am having an issue where colon does not animate when animation is finished, not sure if its your code or the library

**Comment by tablatronix** [comment]
My colon stops flashing when animation is done, does yours do that on your panel ?

**Comment by tablatronix** [comment]
oh that makes sense the examples are not calling drawnumbers when animation is finished so the colon just stays the way it is,  I guess you could always call drawnum, or call drawcolon yourself, but then it doesnt have the y `  int y = yFinish - (TETRIS_Y_DROP_DEFAULT * this->scale);`

**Comment by witnessmenow** [comment]
If you check out the esp32 example I fixed this exact issue!

**Comment by tablatronix** [comment]
well shoot, I picked the wrong example to be porting

**Comment by witnessmenow** [comment]
Sorry yeah , the esp8266 version is a couple of days behind. I was just
running out of time for the video so I kind of abandoned it!

**Comment by tablatronix** [comment]
tsk tsk bad programmer.. haha
It happens, shrug
