### ISSUE TITLE
RGB LED matrix 64 x 32 P3 can't buy

### ISSUE THREAD

**Issue by LilyGO** [witnessmenow/WiFi-Tetris-Clock#5]
Does the RGB LED Matrix 64 x 32 P4 fit this project? I can't buy P3 for the time being.

Thanks.

**Comment by witnessmenow** [comment]
Yeah it should work fine, my p4 matrix does not connect the E pin so you
might need to omit that from your wiring, but other than that it should work

**Comment by LilyGO** [comment]
Thank you

**Comment by LilyGO** [comment]
![QQ图片20190622184308](https://user-images.githubusercontent.com/31160602/60065758-8ca30480-9737-11e9-9bfa-9aa437bdaa37.jpg)

**Comment by LilyGO** [comment]
It has been successfully run
Can you provide your email address? We have the opportunity to cooperate

**Comment by witnessmenow** [comment]
Hi,

Awesome that you got it working!

My email is listed in the about page of my YouTube channel if you want to
contact me

https://www.youtube.com/user/witnessmenow/about?app=desktop

Thanks,
Brian

**Comment by LilyGO** [comment]
Thank you so much!
